### ISSUE TITLE
Version 2.4.3 and later result in a TypeError. 2.4.2 and earlier do not have this issue.

### ISSUE THREAD

**Issue by keremerkan** [songzh96/homebridge-crestron#16]
Version 2.4.3 and later of the plugin seems to have a bug and this results in the accessories becoming unresponsive.

The Homebridge log is as follows:
```
[2/13/2022, 3:38:12 PM] [CresKit] TypeError: Cannot read properties of undefined (reading 'log')
    at closeGetStatus (/usr/lib/node_modules/homebridge-creskit2/index.js:25:10)
    at CresKitAccessory.<anonymous> (/usr/lib/node_modules/homebridge-creskit2/index.js:147:17)
    at Object.onceWrapper (node:events:640:26)
    at EventEmitter.emit (node:events:520:28)
    at CresKit.<anonymous> (/usr/lib/node_modules/homebridge-creskit2/index.js:89:34)
    at /usr/lib/node_modules/homebridge-creskit2/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/usr/lib/node_modules/homebridge-creskit2/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/lib/node_modules/homebridge-creskit2/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/usr/lib/node_modules/homebridge-creskit2/node_modules/async/dist/async.js:3172:5)
    at CresKit.<anonymous> (/usr/lib/node_modules/homebridge-creskit2/index.js:84:19)
```

**Comment by songzh96** [comment]
Hi。 I released a new version， Try update

**Comment by keremerkan** [comment]
Thanks for the fast support. I can confirm that the new version fixes the issue.
